apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-intro
  labels:
    app: kube-intro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-intro
  template:
    metadata:
      name: kube-intro
      labels:
        app: kube-intro
    spec:
      containers:
        - name: kube-intro
          image: com-example/kube-intro
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: mongo_user
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: mongo_pwd
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo-creds
            - name: mongo_url
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: kube-intro
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
