apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-re
  labels:
    app: test-re
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-re
  template:
    metadata:
      name: test-re
      labels:
        app: test-re
    spec:
      containers:
        - name: test-re
          image: Image
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      